### ISSUE TITLE
[Feature Request] Support color

### ISSUE THREAD

**Issue by Asthestarsfalll** [orzation/bobibo#11]
Use escape character `\033[` to add color. I am not familiar with go, so I reimplement your code in Python. You may refer the process [here](https://github.com/Asthestarsfalll/img2art/blob/main/img2art/utils.py#L49).
![2024-01-21_23-18](https://github.com/orzation/bobibo/assets/72954905/8ddff9b4-4204-47a6-b001-15dc072d2488)

**Comment by msqtt** [comment]
Thank you for bringing this to our attention! Adding support for color using escape characters like \033[ is indeed a great idea.

**Comment by msqtt** [comment]
I will close this issue for now, but please feel free to reopen it if you have any further questions or if you'd like to track the progress of this feature.
